name: CI

on: [push]

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout

    - name: Set up Rust
      uses: actions-rs/toolchain
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Build
      run: cargo build

    - name: Zip .exe files
      run: |
        zip -r exe_files.zip . -i target/*.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: exe-files
        path: exe_files.zip