name: CI

on: [push, pull_request]

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Rust
      uses: hecrj/setup-rust-action@v2.0.1
      with:
        profile: minimal

    - name: Build
      run: cargo build

    - name: Run tests
      run: cargo test

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux-executable
        path: /target/debug/todo