name: CI

on: [push, pull_request]

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Rust
      uses: hecrj/setup-rust-action@v2.0.1
      with:
        profile: minimal

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Zip .exe files
      run: |
        zip -r exe_files.zip target/*.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: exe-files
        path: exe_files.zip